### ISSUE TITLE
Getting fitness information over generations

### ISSUE THREAD

**Issue by KevinLi-USDA** [benitezfj/nsga3r#12]
Hi,

Thanks for making this package!

I am trying to understand the performance of my `rmoo` results. I know that vignettes are forthcoming on using `getFitness()`, `getMetrics()` and `summary()`. However, I'd like to get an idea of how the fitness has converged over generations, similar to when one plots the results in the `GA` package. Is there a way to do this? I also note that in my nsga2 results the slots for `summary`, `solution`, and `fitnessValue` are missing data. Could I be missing a step or input in the process?

I appreciate any hints or assistance!

Thanks,
Kevin

**Comment by benitezfj** [comment]
Kevin,

First of all, I am glad you find our package useful. Regarding your question, I would like to clarify a few points first. 

The difference in measuring fitness convergence in the `GA ` package and `rmoo` lies mainly in the number of objectives. In GA, being single-objective, the results can be easily observed in a plot, and it is expected that after a number of generations with no changes in the results, it is assumed to have converged. On the other hand, rmoo evaluates multiple objectives, this task cannot be assessed graphically (at least for problems with more than 3 objectives). 

We had worked on the `getMetrics` method that you mentioned to perform this calculation automatically when rmoo is executed with the `summary = TRUE` argument, but due to time constraints, we have not been able to finish the `progress` method, which is the one executed when summary = TRUE.

The way I would recommend verifying fitness convergence is through the `monitor` argument, passing a custom R function in which you check certain performance metrics using the first non-dominated front. Below, I show an example reusing code that is intended to be used in the progress method:

```
library(rmoo)

# This is the custom R function that will measure the performance metrics and print them in each iteration. It can be modified to save the output to a flat file instead of printing it.
measure_metric <- function(object, ...) {
  callArgs <- as.list(...)
  number_objectives <- ncol(object@fitness)
  nullRP <- is.null(callArgs$ref_dirs)

  iteration <- object@iter
  first <- object@f[[1]]
  first_front_fit <- object@fitness[first, ]
  first_front_pop <- object@population[first, ]
  first_cd <- object@crowdingDistance[first, ]

  if("ecr" %in% rownames(utils::installed.packages())){
    if (!nullRP) {
      gd <- ecr::computeGenerationalDistance(t(object@fitness), t(callArgs$ref_dirs))
      igd <- ecr::computeInvertedGenerationalDistance(t(object@fitness), t(callArgs$ref_dirs))
    }
  }
  if("emoa" %in% rownames(utils::installed.packages())){
    if(!nullRP) {
      reference_point <- apply(callArgs$ref_dirs, 2, max)
      hv <- emoa::dominated_hypervolume(points = t(first_front_fit), ref = reference_point)
    }
  }

  # This function will evaluate three performance metrics. For GD and IGD, a lower value means a better approximation to the reference points.
  # For HV, a higher value means a larger area covered by the non-dominated front concerning a reference point.
  if(nullRP) {
    cat("Warning: reference points not provided:\n
	value necessary to evaluate GD and IGD.")
  } else {
    cat("Iter :", object@iter, 
        "Generational Distance:", if (exists("gd")) gd else NA, 
        "Inverted Generational Distance:", if (exists("igd")) igd else NA, 
        "Hypervolumen:", if (exists("hv")) hv else NA, "\n")
  }
}


# As an example, we use the DTLZ1 test problem with three objectives
dtlz1 <- function (x, nobj = 3,...) {
  if (is.null(dim(x))) {
    x <- matrix(x, 1)
  }
  n <- ncol(x)
  y <- matrix(x[, 1:(nobj - 1)], nrow(x))
  z <- matrix(x[, nobj:n], nrow(x))
  g <- 100 * (n - nobj + 1 + rowSums((z - 0.5)^2 - cos(20 *
                                                         pi * (z - 0.5))))
  tmp <- t(apply(y, 1, cumprod))
  tmp <- cbind(t(apply(tmp, 1, rev)), 1)
  tmp2 <- cbind(1, t(apply(1 - y, 1, rev)))
  f <- tmp * tmp2 * 0.5 * (1 + g)
  return(f)
}

# Define the configuration used in the problem instance
BOUND_LOW <- 0 # Lower bounds for each decision variable
BOUND_UP <- 1 # Upper bounds for each decision variable
NGEN <- 500 # Number of generations
CXPB <- 0.8 # Crossover probability
MUTPB <- 0.2 # Mutation probability
NDIM <- 4 # Number of decision variables
NOBJ <- 3 # Number of evaluated objectives


i <- 5 # Seed

# Since we are using a test problem, we take advantage of the optimal values of DTLZ1 to evaluate the performance metrics
dtlz1_pareto <- 0.5 * rmoo::generate_reference_points(3, 12)

res <- rmoo::rmoo(type = "real-valued",
                  algorithm = "NSGA-II",
                  fitness = dtlz1,
                  lower = rep(BOUND_LOW,NDIM),
                  upper = rep(BOUND_UP,NDIM),
                  popSize = MU,
                  maxiter = NGEN,
                  nObj = NOBJ,
                  pcrossover = CXPB,
                  pmutation = MUTPB,
                  monitor = measure_metric,
                  ref_dirs = dtlz1_pareto,
                  summary = FALSE,
                  parallel = FALSE,
                  seed = i)
```

This code will print the following:

```
Iter : 1 Generational Distance: 63.8797 Inverted Generational Distance: 7.811294 Hypervolumen: 0 
Iter : 2 Generational Distance: 46.50957 Inverted Generational Distance: 5.357296 Hypervolumen: 0 
Iter : 3 Generational Distance: 35.01814 Inverted Generational Distance: 3.765545 Hypervolumen: 0 
Iter : 4 Generational Distance: 25.06483 Inverted Generational Distance: 3.765545 Hypervolumen: 0 
Iter : 5 Generational Distance: 18.99327 Inverted Generational Distance: 2.041967 Hypervolumen: 0
. . .
. . .
. . .
Iter : 495 Generational Distance: 0.2887536 Inverted Generational Distance: 0.3321505 Hypervolumen: 0.9682159 
Iter : 496 Generational Distance: 0.2889813 Inverted Generational Distance: 0.3329922 Hypervolumen: 0.9677379 
Iter : 497 Generational Distance: 0.2889513 Inverted Generational Distance: 0.3332182 Hypervolumen: 0.9672561 
Iter : 498 Generational Distance: 0.2890086 Inverted Generational Distance: 0.3328809 Hypervolumen: 0.9678025 
Iter : 499 Generational Distance: 0.2891673 Inverted Generational Distance: 0.3321223 Hypervolumen: 0.9682238 
Iter : 500 Generational Distance: 0.2891238 Inverted Generational Distance: 0.3323144 Hypervolumen: 0.9683381 
```

Considering this, you can measure fitness convergence based on the values ​​measured by the performance metrics over the iterations.

I hope this can be useful to you.

Regards,
Francisco

**Comment by KevinLi-USDA** [comment]
Hi Francisco,

Thank you so much for this detailed reply. I appreciate the additional complexity of monitoring multiple objectives, thanks for pointing this out.

I've been working through the example code you shared, but I am having some trouble. I've made some adjustments that I think helped to solve some issues but now I am not sure how to proceed.
- I was wondering whether `NDIM` and `NOBJ` should both be 3. Otherwise, I get the error: `Error in Fitness[parents, ] <- Crossover$fitness :  number of items to replace is not a multiple of replacement length`.
- I changed the argument `algorithm = "NSGA-II"` to `strategy = "NSGA-II"`, since I think this is the input method in `rmoo`.
- I also had to change the first line of the `measure_metric()` function to `callArgs <- list(...)`, otherwise I would get an error.

However, I am still not able to use the `measure_metric` function to get the same output as you. Instead, I get the message `Warning: reference points not provided: value necessary to evaluate GD and IGD.` Looking at the code in `measure_metric`, it looks like it is expecting the argument `ref_dirs`. However, in line 482 of the `nsga2()` function, there is only one additional argument passed to the the monitor function: `monitor(object = object, number_objective = nObj)`.

Thanks again for any help,
Kevin

**Comment by benitezfj** [comment]
Dear Kevin,

Could you update the version of `rmoo` using this GitHub repository? The `rmoo` version in CRAN works with a wrapper function for `nsga`, `nsga2` and `nsga3`, which could be causing the error when obtaining the data from the `...` argument. We are working to update it in CRAN as soon as possible.

-  Now, pointing your first issue: it seems to be a problem with the number of objectives evaluated, as an exception occurs in `Fitness[parents, ]` when returning the fitness in the crossover operator. I cannot identify exactly what caused this error, but I can give you some guidelines to check on your own. Firstly, `NDIM` refers to the length of the decision variables; for example, if you are evaluating real-number values, if your `NDIM=3`, you would be evaluating 3 real numbers per solution. The `NOBJ` argument refers to the number of objectives to evaluate; this strictly depends on how you design your objective function. rmoo is designed to evaluate the returned value of the objective function and this must be the same length as NOBJ. If the errors persist, you can use the `debug()` function to trace the error.

- The second issue is precisely due to the nomenclature used in the version of rmoo on CRAN. By updating it via GitHub, you should use `algorithm = "NSGA-II"` and the third issue also refers to the version of rmoo from CRAN. With some modifications, you can run the `measure_metric()` function using the version of rmoo you have. On line 430 of `rmoo_main.R`, you will see that this bug was fixed.

I hope these guidelines can help you.

Regards,  
Francisco

**Comment by KevinLi-USDA** [comment]
Dear Francisco,

Thanks for taking the time to explain these solutions. Installing the development version has solved the issues with your example code. I will try to use it to apply to my own project. I appreciate your patience as I'm still learning.

Best regards,
Kevin
